from enum import Enum

class FLAVOR(Enum):
    MUSSARELA = "MUSSARELA", 20
    NAPOLITANA = "NAPOLITANA", 22
    MARGUERITA = "MARGUERITA", 23
    PEPPERONI = "PEPPERONI", 24
    BACON = "BACON", 25
    OLIVES = "OLIVES", 26
    CHAMPIGNON = "CHAMPIGNON", 27
    ONIONS = "ONIONS", 15
    BEEF = "BEEF", 30
    VEGGIE = "VEGGIE", 28
