from enum import Enum

class FLAVOR(Enum):
    MUSSARELA = "MUSSARELA"
    NAPOLITANA = "NAPOLITANA"
    MARGUERITA = "MARGUERITA"
    PEPPERONI = "PEPPERONI"
    BACON = "BACON"
    OLIVES = "OLIVES"
    CHAMPIGNON = "CHAMPIGNON"
    ONIONS = "ONIONS"
    BEEF = "BEEF"
    VEGGIE = "VEGGIE"
